spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 0

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/photography?serverTimezone=Asia/Shanghai&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
