# 系统或全局的配置 （若只需要框架，此文件内的配置不建议删除，建议只修改，视具体情况而定）



# 系统全局配置
global:
  # 系统全局默认编码
  encoding: UTF-8
  # 是否开启swagger (true/false) 默认（为空）：false
  swagger-open: true

# 自定义模块/扩展组件的配置
modules-candy:
  # 动态定时任务模块配置
  candy-task:
    # 是否开启动态定时任务（便于部署时仅开启某一个jar中的定时任务）
    open: false
    # 是否开启集群模式（若开启将在指定间隔时间查询数据中配置是否发送变更，变更后将进行更新）
    cluster: false
    # 集群模式下，从数据库检查并同步定时任务的时间间隔（毫秒） 默认值是 15000 (即15 秒)
    clusterCheckInterval: 15000

dev:
  modules-candy:
    candy-task:
      open: false
      cluster: true
prod:
  global:
    swagger-open: flase


# 接口鉴权相关配置
interface:
  auth:
    # SecurityConstants.java 配置
    # 由于此类的配置需满足各模块的自定义配置，但是此类又是核心包下的，设计只存在一个，且父模块不能直接访问子模块的配置类，因此只能通过读取可访问的存储在类路径中的配置文件来实现
    security:
      jwt_secret: CandyMuj
      req_header: Authorization
      expiration: 7
      token_split: Bearer
      auth_split: Basic
      interface_auth_username: CandyMuj
      interface_auth_password: CandyMuj!123_
      token_generate_enum: ONLY_DEATH
    # 接口参数签名设置
    sign:
      field: sign
      key: SxgKESLGzlw@iH8f
      nonce: nonce_str
      timespan: timespan
      # 接口请求时间戳验证间隔（毫秒）
      limited: 60000
    # 接口鉴权 排除列表，支持通配符 *
    exclude:
      # 静态资源
      - /*.html
      - /*.css
      - /*.js
      - /*.png
      # swagger
      - /swagger-resources*
      - /webjars*
      #- /v2/api-docs
      - /csrf
      - /favicon.ico
      # 其他
      - /test
      - /third/img/code
      # 业务相关
      # xxx
